### ISSUE TITLE
Bug: GvmInfoWindow components are not removed from the map (repeat)

### ISSUE THREAD

**Issue by Tuhtarov** [diegoazh/gmap-vue#327] opened 2024-05-08 02:18 UTC
Hi @diegoazh, I appreciate your work and look forward to your response. 
I made an [example](https://stackblitz.com/edit/vitejs-vite-rxypcq?file=.env) based on your project on stackblitz where you can clearly see that InfoWindow components are not deleted after they are removed from the data source. After clicking on the text in InfoWindow, check the log in the console. In theory, the marker and window should be deleted on the map together, but only the marker is deleted.

_Originally posted by @Tuhtarov in https://github.com/diegoazh/gmap-vue/issues/323#issuecomment-2097371502_

### Describe the bug
GvmInfoWindow components are not deleted (not closed) in a vue template when the object responsible for rendering this component is deleted in a reactive variable.

### Expected behavior
The marker and window should be removed from the map if the element responsible for drawing the marker and window was deleted in the data source.

### Current behavior
Only the marker is removed, the window remains.

### Desktop
OS: windows 10
Browser chrome (123.0.6312.123)

## Versions
Node: v20.11.1
NPM: 10.2.4
VUE: 3.4.21
VITE: 5.2.0

### Package manager
NPM

### Plugin version
2.1.1

**Comment by DartVadius** [comment] 2024-06-24 07:44
Any progress?

**Comment by diegoazh** [comment] 2024-11-07 15:09
Hi, sorry for the delay, I was working hard and too busy.

The issue is not related to the info-windows implementation. It is related to Vue's reactivity and how it works.

How marker is removed, any change is passed to the `opened` prop of the `InfoWindow`; and how the `InfoWindow` is an independent instance/object, it continues being displayed with the same info.

To implement the expected behavior, you need to use a property that you can change and pass to the `InfoWindow` object, in that case, Vue can detect the change, wait until the change is applied to the UI, and then remove the marker.

I updated your example to get the expected behavior. Also, I replaced `ref` with `reactive` and an object to avoid common reactivity issues in Vue v3; you can read more [here](https://stackoverflow.com/a/70517473/5302733). And the example lives [here](https://stackblitz.com/edit/vitejs-vite-urczqw?file=src%2Fcomponents%2FHelloWorld.vue).

I'm going to close this issue, feel free to reopen it if something else happens.

**Closed by diegoazh** 2024-11-07 15:09 UTC
Labels: bug, under investigation

**Comment by diegoazh** [comment] 2024-11-14 13:43
After adding your test to our E2E test suite, I found a small issue with the logic. It isn't a bug, but weird. I'm going to improve it in the next release.
