### ISSUE TITLE
Bug: autocomplete component: The computed property "fields" is already defined as a prop.

### ISSUE THREAD

**Issue by websitevirtuoso** [diegoazh/gmap-vue#118] opened 2020-11-23 03:39 UTC
**Describe the bug**
I am trying to migrate from old vue-gmap plugin to your lib. Got this error
My application using vuetify. Somewhere creating a computed property with the name "fields".
I don't know where but know that your plugin doing the same. 
SO I got next error:

`
[Vue warn]: The computed property "fields" is already defined as a prop.

found in

---> <GmapAutocomplete> at node_modules/gmap-vue/dist/components/autocomplete.vue
       <VCard>
         <PropertyCreate> at src/views/property/Create.vue
           <VMain>
             <BasicLayout> at src/components/layout/Index.vue
               <VApp>
                 <App> at src/App.vue
                   <Root>
`

**Expected behaviour**
Should work without error **The computed property "fields" is already defined as a prop.**

**Current behaviour**
Display error:  **The computed property "fields" is already defined as a prop.**

**Desktop:**
 - OS:  Ubuntu 19.04
 - Browser chrome 
 - Version 86.0.4240.198

## Versions

- Node: 12
- NPM: 6.14.9

## Package manager

- [x] NPM

## Plugin version

- [x] 1.5.0

**Comment by websitevirtuoso** [comment] 2020-11-23 03:40
@diegoazh

**Comment by diegoazh** [comment] 2020-11-24 14:03
@websitevirtuoso can you rewrite this issue but please you don't need to paste your package.json in the issue template because the boot will close your issue, because it doesn't follow our issue template if you want to paste it please leave it in a comment after creating the issue.

**Comment by websitevirtuoso** [comment] 2020-11-24 19:09
Package json


`
{
  "name": "ecom-dashboard",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build && rm -rf ./dist/**/*.js.map",
    "lint": "vue-cli-service lint",
    "apollo": "vue-cli-service apollo:watch",
    "apollo:run": "vue-cli-service apollo:run"
  },
  "dependencies": {
    "@casl/ability": "^4.1.6",
    "@casl/vue": "^1.1.1",
    "@sentry/browser": "^5.27.4",
    "@sentry/integrations": "^5.27.4",
    "@sentry/webpack-plugin": "^1.13.0",
    "core-js": "^3.7.0",
    "cropperjs": "^1.5.9",
    "gmap-vue": "^1.5.0",
    "graphql-type-json": "^0.3.2",
    "ramda": "^0.27.1",
    "tiptap-vuetify": "^2.24.0",
    "vee-validate": "^2.2.15",
    "vue": "^2.6.12",
    "vue-2-crumbs": "^0.5.4",
    "vue-apollo": "^3.0.5",
    "vue-moment": "^4.1.0",
    "vue-router": "^3.4.9",
    "vuedraggable": "^2.24.3",
    "vuetify": "^2.3.18",
    "vuex": "^3.5.1",
    "vuex-i18n": "^1.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.7",
    "@babel/eslint-parser": "^7.12.1",
    "@mdi/font": "^5.8.55",
    "@vue/cli-plugin-babel": "^4.5.9",
    "@vue/cli-plugin-eslint": "^4.5.9",
    "@vue/cli-service": "^4.5.9",
    "@vue/eslint-config-standard": "^5.1.2",
    "eslint": "^7.14.0",
    "eslint-plugin-graphql": "^4.0.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.1.0",
    "eslint-plugin-vue": "^7.1.0",
    "graphql-tag": "^2.11.0",
    "sass": "^1.29.0",
    "sass-loader": "^10.1.0",
    "vue-cli-plugin-apollo": "^0.21.3",
    "vue-cli-plugin-vuetify": "^2.0.7",
    "vue-template-compiler": "^2.6.12",
    "vuetify-loader": "^1.6.0",
    "webpack-bundle-analyzer": "^4.1.0"
  },
  "engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.8.0"
  }
}

`

**Comment by websitevirtuoso** [comment] 2020-11-24 19:12
@diegoazh Thanks for help. I changed message to your template/ Let me know if it works

**Comment by julienperrault** [comment] 2021-07-05 13:26
I've the same problem. 
![image](https://user-images.githubusercontent.com/16414614/124478100-1cf39580-dda5-11eb-8ea0-5063079ffd19.png)

I'm using pug, so that's is my component (with no customs props).
```pug
<template lang="pug">
    gmap-autocomplete
</template>
```

**Comment by websitevirtuoso** [comment] 2021-07-05 21:57
@julienperrault I had to fork and fix it. Almost all issues bot closing. very sad

**Comment by diegoazh** [comment] 2021-11-26 01:16
@julienperrault sorry about that, the bot causes many problems, test the new version 2.0.0 and check the new documentation page to, please let me know if the issue persists @websitevirtuoso all components are working well in the documentation.

**Comment by diegoazh** [comment] 2021-11-26 01:18
@julienperrault about the bot, please try to open a new issue for test and check if the bot works correctly now, I do that and works well for me but I'm not completely sure if it is fixed or not.

**Comment by diegoazh** [comment] 2022-02-11 09:26
@websitevirtuoso @julienperrault can you test the last v2.0.3 and let me know if the bug persists.

**Comment by razukc** [comment] 2022-02-11 10:05
> @websitevirtuoso @julienperrault can you test the last v2.0.3 and let me know if the bug persists.

I've tested it. The issue still exists.
![image](https://user-images.githubusercontent.com/4814921/153572678-5ce6569b-2f31-4524-9ee7-5c2db2b5d1b1.png)

**Comment by diegoazh** [comment] 2022-02-11 17:40
Can you share with me you component @razukc? to reproduce the issue locally, thanks.

**Comment by diegoazh** [comment] 2022-02-11 23:24
I think is fixed on v2.0.4 can you confirm that @razukc?

**Comment by razukc** [comment] 2022-02-15 05:51
> I think is fixed on v2.0.4 can you confirm that @razukc?

I tested it and I confirm that it is working. But for some reason, _yarn add gmap-vue_ is installing gmap-vue@3.0.0. However, the warning is gone now.

**Closed** 2022-02-15 18:05 UTC
Labels: bug, solved

**Comment by dhcmega** [comment] 2022-03-12 19:09
Hi, I'm on 2.0.4 with "@googlemaps/markerclusterer": "^1.0.26", and I'm getting this same error: TypeError: this.$clusterObject.repaint

Is this only fix on v3 or also for v2?
thanks

**Comment by diegoazh** [comment] 2022-03-12 23:13
Hi, that bug was fixed on version 3.

**Comment by dhcmega** [comment] 2022-03-13 04:29
I don't know why I thought v3 was for vue v3. It worked right away. Thanks!
